// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlGitMe7FRn6A50gF1983oDjz9pgK6Qq4',
    appId: '1:537109481474:web:3668167d132912fe443f1b',
    messagingSenderId: '537109481474',
    projectId: 'clinica-de-alternativo',
    authDomain: 'clinica-de-alternativo.firebaseapp.com',
    storageBucket: 'clinica-de-alternativo.appspot.com',
    measurementId: 'G-LKP86JY8B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOTXGZtpzZr3H_DqDby6ipmMkPFGhsOZM',
    appId: '1:537109481474:android:2550a9c41afb16cf443f1b',
    messagingSenderId: '537109481474',
    projectId: 'clinica-de-alternativo',
    storageBucket: 'clinica-de-alternativo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtqZVoTYbFYd5fcGnxyF4ePBuMh9rx4y0',
    appId: '1:537109481474:ios:6cb9eacf7e72a40e443f1b',
    messagingSenderId: '537109481474',
    projectId: 'clinica-de-alternativo',
    storageBucket: 'clinica-de-alternativo.appspot.com',
    iosBundleId: 'com.falcon.clinicaDeAlternativo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtqZVoTYbFYd5fcGnxyF4ePBuMh9rx4y0',
    appId: '1:537109481474:ios:9a27d2823ed172b5443f1b',
    messagingSenderId: '537109481474',
    projectId: 'clinica-de-alternativo',
    storageBucket: 'clinica-de-alternativo.appspot.com',
    iosBundleId: 'com.falcon.clinicaDeAlternativo.RunnerTests',
  );
}
