// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsStaging {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR0FAYMbIhtKV-_0gEdfqCEt5dINrQ1Ho',
    appId: '1:1043011534888:web:261d72abf858228614751d',
    messagingSenderId: '1043011534888',
    projectId: 'clinica-de-alternativo-staging',
    authDomain: 'clinica-de-alternativo-staging.firebaseapp.com',
    storageBucket: 'clinica-de-alternativo-staging.appspot.com',
    measurementId: 'G-QKPCYQ3R0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB-yVmkbBWi8VAgPU93wUZItPzKWhhnMw',
    appId: '1:1043011534888:android:8cdf560bf7c198fc14751d',
    messagingSenderId: '1043011534888',
    projectId: 'clinica-de-alternativo-staging',
    storageBucket: 'clinica-de-alternativo-staging.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQY53bFUzDHank5ImMSqb831HgSbp-dio',
    appId: '1:1043011534888:ios:3313dd901a72c86d14751d',
    messagingSenderId: '1043011534888',
    projectId: 'clinica-de-alternativo-staging',
    storageBucket: 'clinica-de-alternativo-staging.appspot.com',
    iosBundleId: 'com.falcon.clinicaDeAlternativo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQY53bFUzDHank5ImMSqb831HgSbp-dio',
    appId: '1:1043011534888:ios:078cb260460b071f14751d',
    messagingSenderId: '1043011534888',
    projectId: 'clinica-de-alternativo-staging',
    storageBucket: 'clinica-de-alternativo-staging.appspot.com',
    iosBundleId: 'com.falcon.clinicaDeAlternativo.RunnerTests',
  );
}
